from enum import Enum;
class DIAGNOSE_PARAMETER:
	NONE = 'NONE';
	DYNAMIC_EFFICIENCY   = 'DYNAMIC_EFFICIENCY';
	SECONDARY_CIRCULATION = 'SECONDARY_CIRCULATION';

class GEOMETRY:
	SPHERICAL   = 'SPHERICAL';
	CYLINDRICAL = 'CYLINDRICAL';
	CARTESIAN = 'CARTESIAN';

class DENSITY:
	NORMAL = 'DENSITY_NORMAL';
	BOUSSINESQ = 'DENSITY_BOUSSINESQ';
	
class OPERATOR_COMPLEXITY:
	BARO_ALL = 'BARO_ALL';
	BAROTROPIC = 'BAROTROPIC';
	BAROCLINIC = 'BAROCLINIC';
	
	